/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginregister;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

<<<<<<< HEAD
=======

>>>>>>> ed678473a414b2a7c300a6eed6292909751f5e0c
/**
 *
 * @author 1styrGroupB
 */
public class CashierManagement extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public CashierManagement() {
        initComponents();
        this.setLocationRelativeTo(null);

        cashierdisplayproducts();
        cashierdisplaytransaction();
        comboSql();
    }

    public void cashierdisplayproducts() {
        DefaultTableModel producttable = (DefaultTableModel) tableproductdisplay.getModel();
        int count = 0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_management_system", "root", "")) {
                Statement stmt = con.createStatement();

                ResultSet datas = stmt.executeQuery("SELECT * FROM `products`");
                while (datas.next()) {
                    count = 1;
                    producttable.addRow(new Object[]{datas.getString("productName"), datas.getString("productPrice"), datas.getString("quantity"), datas.getString("description")});

                }
            }
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    private void comboSql() {
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_management_system", "root", "")) {
            Class.forName("com.mysql.jdbc.Driver");
            String sql = "SELECT * FROM `products` ";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                String productname = rs.getString("productName");
                productscombobox.addItem(productname);
            }

        } catch (Exception e) {

        }
    }
<<<<<<< HEAD

=======
    
>>>>>>> ed678473a414b2a7c300a6eed6292909751f5e0c
    public void cashierdisplaytransaction() {
        DefaultTableModel producttable = (DefaultTableModel) cashiertransacttable.getModel();
        int count = 0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_management_system", "root", "")) {
                Statement stmt = con.createStatement();

                ResultSet datas = stmt.executeQuery("SELECT * FROM `product_sold`");
                while (datas.next()) {
                    count = 1;
                    producttable.addRow(new Object[]{datas.getString("date"), datas.getString("productName"), datas.getString("productQuantity"), datas.getString("totalPrice")});

                }
            }
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            System.out.println(e.getMessage());
        }
    }
<<<<<<< HEAD

=======
    
    
    
>>>>>>> ed678473a414b2a7c300a6eed6292909751f5e0c
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableproductdisplay = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        cashiersoldbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        productquantityfield = new javax.swing.JTextField();
        productpricefield = new javax.swing.JTextField();
        productscombobox = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        datesoldlabel = new javax.swing.JLabel();
        productnamelabel = new javax.swing.JLabel();
        productquantitylabel = new javax.swing.JLabel();
        producttotallabel = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        logoutcashierbtn = new javax.swing.JButton();
        checktransactionbtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cashiertransacttable = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Available Products");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 380, 50));

        tableproductdisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Product Price", "Available Quantity", "Description"
            }
        ));
        tableproductdisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableproductdisplayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableproductdisplay);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1160, 210));

        jPanel7.setBackground(new java.awt.Color(0, 204, 153));

<<<<<<< HEAD
        cashiersoldbtn.setText("Sell");
=======
        cashiersoldbtn.setText("Sold");
>>>>>>> ed678473a414b2a7c300a6eed6292909751f5e0c
        cashiersoldbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cashiersoldbtnMouseClicked(evt);
            }
        });

        jLabel6.setText("Product Name:");

        jLabel7.setText("Total:");

        jLabel8.setText("Quantity:");

        productquantityfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                productquantityfieldKeyReleased(evt);
            }
        });

        productscombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a Product..." }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(productscombobox, 0, 260, Short.MAX_VALUE)
                    .addComponent(productquantityfield)
                    .addComponent(productpricefield))
                .addGap(84, 84, 84))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cashiersoldbtn)
                .addGap(217, 217, 217))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productscombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(34, 34, 34)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(productquantityfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productpricefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(cashiersoldbtn)
                .addGap(42, 42, 42))
        );

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 520, 290));

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Transaction");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        jPanel9.setBackground(new java.awt.Color(204, 255, 204));

        title.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        title.setText("Jul's Agri-Suply");

        datesoldlabel.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N

        productnamelabel.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N

        productquantitylabel.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N

        producttotallabel.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N

        title1.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        title1.setText("Canlaon City, Negros Oriental");

        title2.setFont(new java.awt.Font("Monospaced", 3, 16)); // NOI18N
        title2.setText("To God Be the Glory");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 135, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(datesoldlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                            .addComponent(productnamelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(productquantitylabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(producttotallabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(datesoldlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productnamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productquantitylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(producttotallabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 520, 290));

        logoutcashierbtn.setText("Log Out");
        logoutcashierbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutcashierbtnMouseClicked(evt);
            }
        });
        jPanel3.add(logoutcashierbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 680, 160, 40));

        checktransactionbtn.setText("Check Transaction");
        checktransactionbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checktransactionbtnMouseClicked(evt);
            }
        });
        jPanel3.add(checktransactionbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 680, 180, 40));

        jTabbedPane1.addTab("", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cashiertransacttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Product Name", "Quantity", "Total Cost"
            }
        ));
        jScrollPane2.setViewportView(cashiertransacttable);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 1140, 250));

        jPanel10.setBackground(new java.awt.Color(0, 102, 102));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Your Transaction");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 380, 50));

        jButton1.setText("Back");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 550, 130, 40));

        jTabbedPane1.addTab("", jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Courier New", 3, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 204));
        jLabel9.setText("Cashier's Management");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 380, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1199, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableproductdisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableproductdisplayMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableproductdisplayMouseClicked

    private void cashiersoldbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cashiersoldbtnMouseClicked
<<<<<<< HEAD

        LocalDateTime myDateObj = LocalDateTime.now();
        DateTimeFormatter orderDate = DateTimeFormatter.ofPattern("E, MMM dd yyyy");

        String newOrderDate = myDateObj.format(orderDate);
        String productname = this.productscombobox.getSelectedItem().toString();
        String price = this.productpricefield.getText();
        String quantity = this.productquantityfield.getText();

=======
       
        LocalDateTime myDateObj = LocalDateTime.now();
        DateTimeFormatter orderDate = DateTimeFormatter.ofPattern("E, MMM dd yyyy");
        
         String newOrderDate = myDateObj.format(orderDate);
        String productname = this.productscombobox.getSelectedItem().toString();
        String price = this.productpricefield.getText();
        String quantity = this.productquantityfield.getText();
        

        
>>>>>>> ed678473a414b2a7c300a6eed6292909751f5e0c
        if ("Choose a Product...".equals(this.productscombobox.getSelectedItem()) || this.productquantityfield.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Choose a product...", "Alert", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(null, "Invalid Quantity!", "Alert", JOptionPane.ERROR_MESSAGE);
            this.productpricefield.setText("");

        } else {
<<<<<<< HEAD
=======
           
>>>>>>> ed678473a414b2a7c300a6eed6292909751f5e0c

            this.title.setText("Jul' Agri-Supply");
            this.datesoldlabel.setText("Date: " + myDateObj.format(orderDate));
            this.productnamelabel.setText("Product Name: " + (String) this.productscombobox.getSelectedItem());
            this.productquantitylabel.setText("Quantity: " + Integer.parseInt(this.productquantityfield.getText()) + " pack/s");
            this.producttotallabel.setText("Total: Php " + Integer.parseInt(this.productpricefield.getText()) + ".00");

            try {
                DefaultTableModel transactionTableModel = (DefaultTableModel) cashiertransacttable.getModel();
                Class.forName("com.mysql.jdbc.Driver");
<<<<<<< HEAD

                try (Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_management_system", "root", "")) {
                    Statement stmt = con.createStatement();
                    String query1 = "INSERT INTO `product_sold`(`date`, `productName`, `productQuantity`, `totalPrice`) VALUES"
                            + "('" + newOrderDate + "','" + productname + "','" + quantity + "','" + price + "')";
=======
                
                try (Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_management_system", "root", "")) {
                    Statement stmt = con.createStatement();
                    String query1 = "INSERT INTO `product_sold`(`date`, `productName`, `productQuantity`, `totalPrice`) VALUES"
                            + "('" + newOrderDate + "','" + productname + "','"  + quantity + "','" + price + "')";
>>>>>>> ed678473a414b2a7c300a6eed6292909751f5e0c
                    stmt.executeUpdate(query1);

                    int count;
                    ResultSet data = stmt.executeQuery("SELECT * FROM `product_sold`");
                    if (data.next()) {
<<<<<<< HEAD
=======
                        int qnty = Integer.parseInt(data.getString("productQuantity")) - Integer.parseInt(this.productquantityfield.getText());
                        System.out.println(data.getString("productQuantity"));
                        System.out.println(qnty);

                        String newQnty = Integer.toString(qnty);
                        String query2 = "UPDATE `product_sold` SET `productQuantity`='" + newQnty + "'";
                        stmt.executeUpdate(query2);
>>>>>>> ed678473a414b2a7c300a6eed6292909751f5e0c
                    }

                    ResultSet newData = stmt.executeQuery("SELECT * FROM `product_sold`");
                    while (newData.next()) {
                        count = 0;
                        transactionTableModel.removeRow(count);
                        transactionTableModel.addRow(new Object[]{newData.getString("date"), newData.getString("productName"), newData.getString("productQuantity"), newData.getString("totalPrice")});
                    }
                    con.close();
                }
            } catch (ClassNotFoundException | SQLException e) {
                System.out.println(e);
            }
            this.productscombobox.setSelectedIndex(0);
            this.productquantityfield.setText(null);
            this.productpricefield.setText(null);

        }
    }//GEN-LAST:event_cashiersoldbtnMouseClicked

    private void productquantityfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productquantityfieldKeyReleased
        if ("Choose a Product...".equals(this.productscombobox.getSelectedItem()) || this.productquantityfield.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Choose a product...", "Alert", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(null, "Invalid Quantity!", "Alert", JOptionPane.ERROR_MESSAGE);
            this.productpricefield.setText("");

        } else if ("Osmocote Bloom Booster Controlle".equals(this.productscombobox.getSelectedItem()) || "1".equals(this.productquantityfield.getText()) || "2".equals(this.productquantityfield.getText()) || "3".equals(this.productquantityfield.getText()) || "4".equals(this.productquantityfield.getText()) || "5".equals(this.productquantityfield.getText())) {
            int price = 0;
            try {
                Class.forName("com.mysql.jdbc.Driver");
                try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_management_system", "root", "")) {
                    Statement stmt = con.createStatement();

                    ResultSet datas = stmt.executeQuery("SELECT * FROM `products` WHERE `quantity` = '20'");
                    if (datas.next()) {
                        price = datas.getInt("productPrice");
                    }
                }
            } catch (HeadlessException | ClassNotFoundException | SQLException e) {
                System.out.println(e.getMessage());
            }
            this.productpricefield.setText(Integer.toString(price * Integer.parseInt(this.productquantityfield.getText())));
        } else if ("Vermicast Organic Fertilizer".equals(this.productscombobox.getSelectedItem()) || "1".equals(this.productquantityfield.getText()) || "2".equals(this.productquantityfield.getText()) || "3".equals(this.productquantityfield.getText()) || "4".equals(this.productquantityfield.getText()) || "5".equals(this.productquantityfield.getText())) {
            int price = 0;
            try {
                Class.forName("com.mysql.jdbc.Driver");
                try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_management_system", "root", "")) {
                    Statement stmt = con.createStatement();

                    ResultSet datas = stmt.executeQuery("SELECT * FROM `products` WHERE `quantity` = '25'");
                    if (datas.next()) {
                        price = datas.getInt("productPrice");
                    }
                }
            } catch (HeadlessException | ClassNotFoundException | SQLException e) {
                System.out.println(e.getMessage());
            }
            this.productpricefield.setText(Integer.toString(price * Integer.parseInt(this.productquantityfield.getText())));
<<<<<<< HEAD
        } else if ((this.productscombobox.getSelectedItem() == "Dragon Humus Fertilizer") || ("1".equals(this.productquantityfield.getText())) || ("2".equals(this.productquantityfield.getText())) || "3".equals(this.productquantityfield.getText()) || "4".equals(this.productquantityfield.getText()) || "5".equals(this.productquantityfield.getText())) {
=======
        } else if ((this.productscombobox.getSelectedItem()=="Dragon Humus Fertilizer"  ) || ("1".equals(this.productquantityfield.getText())) || ("2".equals(this.productquantityfield.getText())) || "3".equals(this.productquantityfield.getText()) || "4".equals(this.productquantityfield.getText()) || "5".equals(this.productquantityfield.getText())) {
>>>>>>> ed678473a414b2a7c300a6eed6292909751f5e0c
            int price = 0;
            try {
                Class.forName("com.mysql.jdbc.Driver");
                try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_management_system", "root", "")) {
                    Statement stmt = con.createStatement();

                    ResultSet datas = stmt.executeQuery("SELECT * FROM `products` WHERE `quantity` = '30'");
                    if (datas.next()) {
                        price = datas.getInt("productPrice");
                    }
                }
            } catch (HeadlessException | ClassNotFoundException | SQLException e) {
                System.out.println(e.getMessage());
            }
            this.productpricefield.setText(Integer.toString(price * Integer.parseInt(this.productquantityfield.getText())));
        } else if ("Yara Mila Unik Fertilizer".equals(this.productscombobox.getSelectedItem()) || "1".equals(this.productquantityfield.getText()) || "2".equals(this.productquantityfield.getText()) || "3".equals(this.productquantityfield.getText()) || "4".equals(this.productquantityfield.getText()) || "5".equals(this.productquantityfield.getText())) {
            int price = 0;
            try {
                Class.forName("com.mysql.jdbc.Driver");
                try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_management_system", "root", "")) {
                    Statement stmt = con.createStatement();

                    ResultSet datas = stmt.executeQuery("SELECT * FROM `products` WHERE `quantity` = '10'");
                    if (datas.next()) {
                        price = datas.getInt("productPrice");
                    }
                }
            } catch (HeadlessException | ClassNotFoundException | SQLException e) {
                System.out.println(e.getMessage());
            }
            this.productpricefield.setText(Integer.toString(price * Integer.parseInt(this.productquantityfield.getText())));
        }
    }//GEN-LAST:event_productquantityfieldKeyReleased

    private void checktransactionbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checktransactionbtnMouseClicked
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_checktransactionbtnMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1MouseClicked

    private void logoutcashierbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutcashierbtnMouseClicked
        new LogInPageforUsers().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutcashierbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cashiersoldbtn;
    private javax.swing.JTable cashiertransacttable;
    private javax.swing.JButton checktransactionbtn;
    private javax.swing.JLabel datesoldlabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton logoutcashierbtn;
    private javax.swing.JLabel productnamelabel;
    private javax.swing.JTextField productpricefield;
    private javax.swing.JTextField productquantityfield;
    private javax.swing.JLabel productquantitylabel;
    private javax.swing.JComboBox<String> productscombobox;
    private javax.swing.JLabel producttotallabel;
    private javax.swing.JTable tableproductdisplay;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    // End of variables declaration//GEN-END:variables
}
