/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginregister;

import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;

public class LogInPageforUsers extends javax.swing.JFrame {

    /**
     * Creates new form LogInPageforInventory
     */
    public LogInPageforUsers() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        roleuserbox = new javax.swing.JComboBox<>();
        ipusername = new javax.swing.JTextField();
        ippassword = new javax.swing.JPasswordField();
        ipLogInbtn = new javax.swing.JButton();
        jButtonRegister = new javax.swing.JButton();
        jCheckBoxshowpass = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jButtonReset = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Role:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        roleuserbox.setFont(new java.awt.Font("Courier New", 3, 14)); // NOI18N
        roleuserbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose your role...", "Admin", "Inventory Person", "Cashier" }));
        jPanel1.add(roleuserbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 210, 40));

        ipusername.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        ipusername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ipusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ipusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ipusernameFocusLost(evt);
            }
        });
        jPanel1.add(ipusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 210, 33));

        ippassword.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        ippassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ippassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ippasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ippasswordFocusLost(evt);
            }
        });
        jPanel1.add(ippassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 210, 33));

        ipLogInbtn.setBackground(new java.awt.Color(153, 153, 153));
        ipLogInbtn.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        ipLogInbtn.setText("Log In");
        ipLogInbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 5));
        ipLogInbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ipLogInbtnMouseClicked(evt);
            }
        });
        ipLogInbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipLogInbtnActionPerformed(evt);
            }
        });
        jPanel1.add(ipLogInbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 130, -1));

        jButtonRegister.setBackground(new java.awt.Color(153, 153, 153));
        jButtonRegister.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButtonRegister.setText("Register");
        jButtonRegister.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 5));
        jButtonRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRegisterMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 130, -1));

        jCheckBoxshowpass.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jCheckBoxshowpass.setForeground(new java.awt.Color(0, 102, 102));
        jCheckBoxshowpass.setText("Show Password");
        jCheckBoxshowpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxshowpassActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxshowpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Username:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jButtonReset.setBackground(new java.awt.Color(153, 153, 153));
        jButtonReset.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102), 3));
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 85, -1));

        jLabel3.setFont(new java.awt.Font("Courier New", 3, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" Welcome to Jul's Agri-Supply");
        jLabel3.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 360, 50));

        jLabel4.setBackground(new java.awt.Color(0, 102, 102));
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\1styrGroupB\\Pictures\\Saved Pictures\\loginback (2).png")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 410, 350));

        jLabel7.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("User Verification");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ipusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ipusernameFocusGained
        if (ipusername.getText().trim().toLowerCase().equals("username")) {
            ipusername.setText("");
        }
    }//GEN-LAST:event_ipusernameFocusGained

    private void ipusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ipusernameFocusLost
        // if the text field is equal to username or empty
        // we will set the "username" text in the field
        // on focus lost event

        if (ipusername.getText().trim().equals("")
                || ipusername.getText().trim().toLowerCase().equals("username")) {
            ipusername.setText("username");
        }
    }//GEN-LAST:event_ipusernameFocusLost

    private void ippasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ippasswordFocusGained
        // clear the password field on focus if the text is "password"

        // get the password text
        String pass = String.valueOf(ippassword.getPassword());

        if (pass.trim().toLowerCase().equals("password")) {
            ippassword.setText("");
        }
    }//GEN-LAST:event_ippasswordFocusGained

    private void ippasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ippasswordFocusLost
        // if the password field is equal to password or empty
        // we will set the "password" text in the field
        // on focus lost event

        // get the password text
        String pass = String.valueOf(ippassword.getPassword());

        if (pass.trim().equals("")
                || pass.trim().toLowerCase().equals("password")) {
            ippassword.setText("password");
        }
    }//GEN-LAST:event_ippasswordFocusLost

    private void ipLogInbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ipLogInbtnMouseClicked
     
        String role = roleuserbox.getSelectedItem().toString();
        String uname = ipusername.getText();
        String pass = String.valueOf(ippassword.getPassword());

        if ("Choose your role...".equals(this.roleuserbox.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(this, "Choose your role in the system!", "Alert", JOptionPane.ERROR_MESSAGE);
            if ("".equals(this.ipusername.getText()) && "".equals(this.ippassword.getText())) {
            JOptionPane.showMessageDialog(this, "Invalid Username and Password", "Alert", JOptionPane.ERROR_MESSAGE);
        }
        
        } else {

            try {

                Class.forName("com.mysql.jdbc.Driver");

                try (Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_management_system", "root", "")) {

                    Statement stmt = con.createStatement();
                    
                    String query1 = "SELECT * FROM `user_accounts` WHERE role = '" + role + "' AND username = '" + uname + "' AND password = '" + pass + "'";
                    ResultSet rs = stmt.executeQuery(query1);

                    if (rs.next()) {
                        dispose();//close login page

                        new AdminManagement().setVisible(true);
                        this.setVisible(false);

                    } else {

                        JOptionPane.showMessageDialog(this, "This admin ccount doesn't exist, Register first!", "Alert", JOptionPane.ERROR_MESSAGE);
                        //
                        //                    uname.setText(null);
                        //
                        //                    password.setText(null);
                    }
                }

            } catch (ClassNotFoundException | SQLException e) {

                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_ipLogInbtnMouseClicked

    private void ipLogInbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipLogInbtnActionPerformed
 
    }//GEN-LAST:event_ipLogInbtnActionPerformed

    private void jButtonRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegisterMouseClicked
        Register r = new Register();
        r.setVisible(true);
        r.pack();
        r.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonRegisterMouseClicked

    private void jCheckBoxshowpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxshowpassActionPerformed
        if (evt.getSource() == jCheckBoxshowpass) {
            if (jCheckBoxshowpass.isSelected()) {
                ippassword.setEchoChar((char) 0);
            } else {
                ippassword.setEchoChar('*');
            }
        }
    }//GEN-LAST:event_jCheckBoxshowpassActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        if (evt.getSource() == jButtonReset) {
            ipusername.setText("");
            ippassword.setText("");
        }
    }//GEN-LAST:event_jButtonResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInPageforUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInPageforUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInPageforUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInPageforUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInPageforUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ipLogInbtn;
    private javax.swing.JPasswordField ippassword;
    private javax.swing.JTextField ipusername;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JCheckBox jCheckBoxshowpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> roleuserbox;
    // End of variables declaration//GEN-END:variables
}
