/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginregister;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 1styrGroupB
 */
public class ManageUsers extends javax.swing.JFrame {

    /**
     * Creates new form ManageUsers
     */
    public ManageUsers() {
        initComponents();
        this.setLocationRelativeTo(null);

        manageAdminAccount();
        manageInventoryAccount();
        manageCashierAccount();
    }

    public void manageAdminAccount() {
        DefaultTableModel admintable = (DefaultTableModel) manageadmintable.getModel();
        int count = 0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_management_system", "root", "")) {
                Statement stmt = con.createStatement();

                ResultSet datas = stmt.executeQuery("SELECT * FROM `user_accounts` WHERE role = 'Admin'");
                while (datas.next()) {
                    count = 1;
                    admintable.addRow(new Object[]{datas.getString("id"), datas.getString("role"), datas.getString("name"), datas.getString("contact_number"), datas.getString("address"), datas.getString("username"), datas.getString("password")});

                }
            }
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    public void manageInventoryAccount() {
        DefaultTableModel inventorytable = (DefaultTableModel) manageinventorytable.getModel();
        int count = 0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_management_system", "root", "")) {
                Statement stmt = con.createStatement();

                ResultSet datas = stmt.executeQuery("SELECT * FROM `user_accounts` WHERE role = 'Inventory Person'");
                while (datas.next()) {
                    count = 1;
                    inventorytable.addRow(new Object[]{datas.getString("id"), datas.getString("role"), datas.getString("name"), datas.getString("contact_number"), datas.getString("address"), datas.getString("username"), datas.getString("password")});

                }
            }
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    public void manageCashierAccount() {
        DefaultTableModel cashiertable = (DefaultTableModel) managecashiertable.getModel();
        int count = 0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_management_system", "root", "")) {
                Statement stmt = con.createStatement();

                ResultSet datas = stmt.executeQuery("SELECT * FROM `user_accounts` WHERE role = 'Cashier'");
                while (datas.next()) {
                    count = 1;
                    cashiertable.addRow(new Object[]{datas.getString("id"), datas.getString("role"), datas.getString("name"), datas.getString("contact_number"), datas.getString("address"), datas.getString("username"), datas.getString("password")});

                }
            }
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        manageadminbtn = new javax.swing.JButton();
        manageinventorybtn = new javax.swing.JButton();
        managecashierbtn = new javax.swing.JButton();
        manageexitbtn = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        manageadminacc = new javax.swing.JPanel();
        dunnopanel = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        manageadmintable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        updateadminaccbtn = new javax.swing.JButton();
        deleteadminaccbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        idfield = new javax.swing.JTextField();
        namefield = new javax.swing.JTextField();
        passwordfield = new javax.swing.JTextField();
        rolefield = new javax.swing.JTextField();
        contactfield = new javax.swing.JTextField();
        addressfield = new javax.swing.JTextField();
        usernamefield = new javax.swing.JTextField();
        manageinventoryacc = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        manageinventorytable = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        manageipupdatebtn = new javax.swing.JButton();
        manageipdeletebtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        updateadminaccbtn1 = new javax.swing.JButton();
        deleteadminaccbtn1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        ipidfield = new javax.swing.JTextField();
        ipnamefield = new javax.swing.JTextField();
        ippasswordfield = new javax.swing.JTextField();
        iprolefield = new javax.swing.JTextField();
        ipcontactfield = new javax.swing.JTextField();
        ipaddressfield = new javax.swing.JTextField();
        ipusernamefield = new javax.swing.JTextField();
        managecashieracc = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        managecashiertable = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        cashierupdatebtn = new javax.swing.JButton();
        cashierdeletebtn = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        manageipupdatebtn1 = new javax.swing.JButton();
        manageipdeletebtn1 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        updateadminaccbtn2 = new javax.swing.JButton();
        deleteadminaccbtn2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        cashieridfield = new javax.swing.JTextField();
        cashiernamefield1 = new javax.swing.JTextField();
        cashierpasswordfield = new javax.swing.JTextField();
        cashierrolefield = new javax.swing.JTextField();
        cashiercontactfield = new javax.swing.JTextField();
        cashieraddressfield = new javax.swing.JTextField();
        cashierusernamefield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Courier New", 3, 45)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("Manage Users");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(381, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(301, 301, 301))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 80));

        jPanel4.setBackground(new java.awt.Color(102, 0, 0));

        manageadminbtn.setText("Admin Account");
        manageadminbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageadminbtnMouseClicked(evt);
            }
        });

        manageinventorybtn.setText("Inventory Account");
        manageinventorybtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageinventorybtnMouseClicked(evt);
            }
        });

        managecashierbtn.setText("Cashier Account");
        managecashierbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managecashierbtnMouseClicked(evt);
            }
        });

        manageexitbtn.setText("Back");
        manageexitbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageexitbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(manageexitbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageadminbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageinventorybtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(managecashierbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manageadminbtn)
                .addGap(37, 37, 37)
                .addComponent(manageinventorybtn)
                .addGap(38, 38, 38)
                .addComponent(managecashierbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(manageexitbtn)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 360, 160, 240));

        dunnopanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(51, 0, 0));

        jLabel2.setFont(new java.awt.Font("Courier New", 3, 35)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 204));
        jLabel2.setText("Manage Admin Account");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(458, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        dunnopanel.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 70));

        manageadmintable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Admin_ID", "Role", "Name", "Contact No.", "Address", "Username", "Password"
            }
        ));
        manageadmintable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageadmintableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(manageadmintable);

        dunnopanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 890, 170));

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateadminaccbtn.setText("Update");
        updateadminaccbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateadminaccbtnMouseClicked(evt);
            }
        });
        jPanel3.add(updateadminaccbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        deleteadminaccbtn.setText("Delete");
        deleteadminaccbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteadminaccbtnMouseClicked(evt);
            }
        });
        jPanel3.add(deleteadminaccbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        dunnopanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 220, 60));

        jLabel5.setText("Password:");
        dunnopanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, -1, -1));

        jLabel6.setText("Admin_ID:");
        dunnopanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel7.setText("Name:");
        dunnopanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel8.setText("Role:");
        dunnopanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel9.setText("Contact No.");
        dunnopanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel10.setText("Address:");
        dunnopanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jLabel11.setText("Username:");
        dunnopanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, -1, -1));
        dunnopanel.add(idfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 230, -1));
        dunnopanel.add(namefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 230, -1));
        dunnopanel.add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 230, -1));
        dunnopanel.add(rolefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 230, -1));
        dunnopanel.add(contactfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 230, -1));
        dunnopanel.add(addressfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 230, -1));
        dunnopanel.add(usernamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 230, -1));

        javax.swing.GroupLayout manageadminaccLayout = new javax.swing.GroupLayout(manageadminacc);
        manageadminacc.setLayout(manageadminaccLayout);
        manageadminaccLayout.setHorizontalGroup(
            manageadminaccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dunnopanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        manageadminaccLayout.setVerticalGroup(
            manageadminaccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dunnopanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", manageadminacc);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(51, 0, 0));

        jLabel3.setFont(new java.awt.Font("Courier New", 3, 35)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 204));
        jLabel3.setText("Manage Inventory Person Accounts");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(206, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 70));

        manageinventorytable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IP_ID", "Role", "Name", "Contact No.", "Address", "Username", "Password"
            }
        ));
        manageinventorytable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageinventorytableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(manageinventorytable);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 890, 160));

        jPanel10.setBackground(new java.awt.Color(102, 0, 102));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageipupdatebtn.setText("Update");
        manageipupdatebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageipupdatebtnMouseClicked(evt);
            }
        });
        jPanel10.add(manageipupdatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        manageipdeletebtn.setText("Delete");
        manageipdeletebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageipdeletebtnMouseClicked(evt);
            }
        });
        jPanel10.add(manageipdeletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jPanel6.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 230, 60));

        jPanel5.setBackground(new java.awt.Color(102, 0, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateadminaccbtn1.setText("Update");
        updateadminaccbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateadminaccbtn1MouseClicked(evt);
            }
        });
        jPanel5.add(updateadminaccbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        deleteadminaccbtn1.setText("Delete");
        deleteadminaccbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteadminaccbtn1MouseClicked(evt);
            }
        });
        jPanel5.add(deleteadminaccbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jPanel6.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 220, 60));

        jLabel12.setText("Password:");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, -1, -1));

        jLabel13.setText("IP_ID:");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel14.setText("Name:");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel15.setText("Role:");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel16.setText("Contact No.");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel17.setText("Address:");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jLabel18.setText("Username:");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, -1, -1));
        jPanel6.add(ipidfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 230, -1));
        jPanel6.add(ipnamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 230, -1));
        jPanel6.add(ippasswordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 230, -1));
        jPanel6.add(iprolefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 230, -1));
        jPanel6.add(ipcontactfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 230, -1));
        jPanel6.add(ipaddressfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 230, -1));
        jPanel6.add(ipusernamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 230, -1));

        javax.swing.GroupLayout manageinventoryaccLayout = new javax.swing.GroupLayout(manageinventoryacc);
        manageinventoryacc.setLayout(manageinventoryaccLayout);
        manageinventoryaccLayout.setHorizontalGroup(
            manageinventoryaccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        manageinventoryaccLayout.setVerticalGroup(
            manageinventoryaccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", manageinventoryacc);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        managecashiertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cashiers_ID", "Role", "Name", "Contact No.", "Address", "Username", "Password"
            }
        ));
        managecashiertable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managecashiertableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(managecashiertable);

        jPanel7.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 890, 160));

        jPanel11.setBackground(new java.awt.Color(51, 0, 0));

        jLabel4.setFont(new java.awt.Font("Courier New", 3, 35)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 204));
        jLabel4.setText("Manage Cashiers Accounts");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(374, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(26, 26, 26))
        );

        jPanel7.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 70));

        jPanel12.setBackground(new java.awt.Color(102, 0, 102));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cashierupdatebtn.setText("Update");
        cashierupdatebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cashierupdatebtnMouseClicked(evt);
            }
        });
        jPanel12.add(cashierupdatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        cashierdeletebtn.setText("Delete");
        cashierdeletebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cashierdeletebtnMouseClicked(evt);
            }
        });
        jPanel12.add(cashierdeletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jPanel7.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 230, 60));

        jPanel13.setBackground(new java.awt.Color(102, 0, 102));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageipupdatebtn1.setText("Update");
        manageipupdatebtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageipupdatebtn1MouseClicked(evt);
            }
        });
        jPanel13.add(manageipupdatebtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        manageipdeletebtn1.setText("Delete");
        manageipdeletebtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageipdeletebtn1MouseClicked(evt);
            }
        });
        jPanel13.add(manageipdeletebtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jPanel7.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 230, 60));

        jPanel14.setBackground(new java.awt.Color(102, 0, 102));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateadminaccbtn2.setText("Update");
        updateadminaccbtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateadminaccbtn2MouseClicked(evt);
            }
        });
        jPanel14.add(updateadminaccbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        deleteadminaccbtn2.setText("Delete");
        deleteadminaccbtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteadminaccbtn2MouseClicked(evt);
            }
        });
        jPanel14.add(deleteadminaccbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jPanel7.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 220, 60));

        jLabel19.setText("Password:");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, -1, -1));

        jLabel20.setText("IP_ID:");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel21.setText("Name:");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel22.setText("Role:");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel23.setText("Contact No.");
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel24.setText("Address:");
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jLabel25.setText("Username:");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, -1, -1));
        jPanel7.add(cashieridfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 230, -1));
        jPanel7.add(cashiernamefield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 230, -1));
        jPanel7.add(cashierpasswordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 230, -1));
        jPanel7.add(cashierrolefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 230, -1));
        jPanel7.add(cashiercontactfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 230, -1));
        jPanel7.add(cashieraddressfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 230, -1));
        jPanel7.add(cashierusernamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 230, -1));

        javax.swing.GroupLayout managecashieraccLayout = new javax.swing.GroupLayout(managecashieracc);
        managecashieracc.setLayout(managecashieraccLayout);
        managecashieraccLayout.setHorizontalGroup(
            managecashieraccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        managecashieraccLayout.setVerticalGroup(
            managecashieraccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", managecashieracc);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 890, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageadminbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageadminbtnMouseClicked
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_manageadminbtnMouseClicked

    private void manageinventorybtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageinventorybtnMouseClicked
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_manageinventorybtnMouseClicked

    private void managecashierbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managecashierbtnMouseClicked
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_managecashierbtnMouseClicked

    private void manageexitbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageexitbtnMouseClicked
        new AdminManagement().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manageexitbtnMouseClicked

    private void updateadminaccbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateadminaccbtnMouseClicked
        DefaultTableModel manageadmintbl = (DefaultTableModel) manageadmintable.getModel();

        if ("".equals(idfield.getText()) && "".equals(rolefield.getText())) {
            JOptionPane.showMessageDialog(null, "No Selected Product!", "Alert", JOptionPane.ERROR_MESSAGE);
        } else {
            String adminid = (String) manageadmintbl.getValueAt(manageadmintable.getSelectedRow(), 0);

            int count;
            try {
                Class.forName("com.mysql.jdbc.Driver");
                try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_management_system", "root", "")) {
                    Statement stmt = con.createStatement();
                    Statement stmt1 = con.createStatement();
                    String query = "UPDATE `user_accounts` SET `role`='" + this.rolefield.getText() + "',`Name`='" + this.namefield.getText() + "',`contact_number`='" + this.contactfield.getText() + "',`address`='" + this.addressfield.getText() + "',`username`='" + this.usernamefield.getText() + "',`password`='" + this.passwordfield.getText() + "' WHERE  id = '" + adminid + "'";
                    stmt.execute(query);
                    this.cashieridfield.setText(null);
                    this.cashiernamefield1.setText(null);
                    this.cashierrolefield.setText(null);
                    this.cashiercontactfield.setText(null);
                    this.cashieraddressfield.setText(null);
                    this.cashierusernamefield.setText(null);
                    this.cashierpasswordfield.setText(null);

                    ResultSet datas = stmt1.executeQuery("SELECT * FROM `user_accounts`");
                    while (datas.next()) {
                        count = 0;
                        manageadmintbl.removeRow(count);
                        manageadmintbl.addRow(new Object[]{datas.getString("id"), datas.getString("role"), datas.getString("Name"), datas.getString("contact_number"), datas.getString("address"), datas.getString("username"), datas.getString("password")});
                    }

                    con.close();
                    JOptionPane.showMessageDialog(null, "Successfully Updated.", "Alert", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (HeadlessException | ClassNotFoundException | SQLException e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_updateadminaccbtnMouseClicked

    private void deleteadminaccbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteadminaccbtnMouseClicked
        DefaultTableModel userTableModel = (DefaultTableModel) manageadmintable.getModel();
        if (manageadmintable.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "Unsuccessful!", "Alert", JOptionPane.ERROR_MESSAGE);
        } else {

            String adminid = (String) userTableModel.getValueAt(manageadmintable.getSelectedRow(), 0);
            try {
                Class.forName("com.mysql.jdbc.Driver");
                try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_management_system", "root", "")) {
                    Statement stmt = con.createStatement();
                    String query = "DELETE FROM user_accounts WHERE id= " + adminid + "";
                    stmt.execute(query);
                    con.close();
                    JOptionPane.showMessageDialog(null, "Successfully Deleted.", "Alert", JOptionPane.INFORMATION_MESSAGE);
                    userTableModel.removeRow(manageadmintable.getSelectedRow());
                }
            } catch (HeadlessException | ClassNotFoundException | SQLException e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(null, "Unsuccessful!", "Alert", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteadminaccbtnMouseClicked

    private void manageadmintableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageadmintableMouseClicked
        //to textfield
        DefaultTableModel manageadmintbl = (DefaultTableModel) manageadmintable.getModel();

        String tblid = (String) manageadmintbl.getValueAt(manageadmintable.getSelectedRow(), 0);
        String tblrole = (String) manageadmintbl.getValueAt(manageadmintable.getSelectedRow(), 1);
        String tblname = (String) manageadmintbl.getValueAt(manageadmintable.getSelectedRow(), 2);
        String tblcontact = (String) manageadmintbl.getValueAt(manageadmintable.getSelectedRow(), 3);
        String tbladdress = (String) manageadmintbl.getValueAt(manageadmintable.getSelectedRow(), 4);
        String tblusername = (String) manageadmintbl.getValueAt(manageadmintable.getSelectedRow(), 5);
        String tblpass = (String) manageadmintbl.getValueAt(manageadmintable.getSelectedRow(), 6);

        this.idfield.setText(tblid);
        this.namefield.setText(tblname);
        this.rolefield.setText(tblrole);
        this.contactfield.setText(tblcontact);
        this.addressfield.setText(tbladdress);
        this.usernamefield.setText(tblusername);
        this.passwordfield.setText(tblpass);

    }//GEN-LAST:event_manageadmintableMouseClicked

    private void updateadminaccbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateadminaccbtn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_updateadminaccbtn1MouseClicked

    private void deleteadminaccbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteadminaccbtn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteadminaccbtn1MouseClicked

    private void manageinventorytableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageinventorytableMouseClicked

        DefaultTableModel manageiptbl = (DefaultTableModel) manageinventorytable.getModel();

        String ipid = (String) manageiptbl.getValueAt(manageinventorytable.getSelectedRow(), 0);
        String iprole = (String) manageiptbl.getValueAt(manageinventorytable.getSelectedRow(), 1);
        String ipname = (String) manageiptbl.getValueAt(manageinventorytable.getSelectedRow(), 2);
        String ipcontact = (String) manageiptbl.getValueAt(manageinventorytable.getSelectedRow(), 3);
        String ipaddress = (String) manageiptbl.getValueAt(manageinventorytable.getSelectedRow(), 4);
        String ipusername = (String) manageiptbl.getValueAt(manageinventorytable.getSelectedRow(), 5);
        String ippass = (String) manageiptbl.getValueAt(manageinventorytable.getSelectedRow(), 6);

        this.ipidfield.setText(ipid);
        this.ipnamefield.setText(ipname);
        this.iprolefield.setText(iprole);
        this.ipcontactfield.setText(ipcontact);
        this.ipaddressfield.setText(ipaddress);
        this.ipusernamefield.setText(ipusername);
        this.ippasswordfield.setText(ippass);
    }//GEN-LAST:event_manageinventorytableMouseClicked

    private void manageipupdatebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageipupdatebtnMouseClicked
        DefaultTableModel manageiptbl = (DefaultTableModel) manageinventorytable.getModel();

        if ("".equals(ipidfield.getText()) && "".equals(iprolefield.getText())) {
            JOptionPane.showMessageDialog(null, "No Selected Product!", "Alert", JOptionPane.ERROR_MESSAGE);
        } else {
            String ipid = (String) manageiptbl.getValueAt(manageinventorytable.getSelectedRow(), 0);

            int count;
            try {
                Class.forName("com.mysql.jdbc.Driver");
                try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_management_system", "root", "")) {
                    Statement stmt = con.createStatement();
                    Statement stmt1 = con.createStatement();
                    String query = "UPDATE `user_accounts` SET `role`='" + this.iprolefield.getText() + "',`Name`='" + this.ipnamefield.getText() + "',`contact_number`='" + this.ipcontactfield.getText() + "',`address`='" + this.ipaddressfield.getText() + "',`username`='" + this.ipusernamefield.getText() + "',`password`='" + this.ippasswordfield.getText() + "' WHERE  id = '" + ipid + "'";
                    stmt.execute(query);
                    this.ipidfield.setText(null);
                    this.ipnamefield.setText(null);
                    this.iprolefield.setText(null);
                    this.ipcontactfield.setText(null);
                    this.ipaddressfield.setText(null);
                    this.ipusernamefield.setText(null);
                    this.ippasswordfield.setText(null);

                    ResultSet datas = stmt1.executeQuery("SELECT * FROM `user_accounts`");
                    while (datas.next()) {
                        count = 0;
                        manageiptbl.removeRow(count);
                        manageiptbl.addRow(new Object[]{datas.getString("id"), datas.getString("role"), datas.getString("Name"), datas.getString("contact_number"), datas.getString("address"), datas.getString("username"), datas.getString("password")});
                    }

                    con.close();
                    JOptionPane.showMessageDialog(null, "Successfully Updated.", "Alert", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (HeadlessException | ClassNotFoundException | SQLException e) {
                System.out.println(e.getMessage());
            }
        }







//        DefaultTableModel manageiptbl = (DefaultTableModel) manageinventorytable.getModel();
//
//        if ("".equals(ipidfield.getText()) && "".equals(iprolefield.getText())) {
//            JOptionPane.showMessageDialog(null, "No Selected Product!", "Alert", JOptionPane.ERROR_MESSAGE);
//        } else {
//            String ipid = (String) manageiptbl.getValueAt(manageinventorytable.getSelectedRow(), 0);
//
//            int count;
//            try {
//                Class.forName("com.mysql.jdbc.Driver");
//                try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_management_system", "root", "")) {
//                    Statement stmt = con.createStatement();
//                    Statement stmt1 = con.createStatement();
//                    String query = "UPDATE `user_accounts` SET `role`='" + this.iprolefield.getText() + "',`Name`='" + this.ipnamefield.getText() + "',`contact_number`='" + this.ipcontactfield.getText() + "',`address`='" + this.ipaddressfield.getText() + "',`username`='" + this.ipusernamefield.getText() + "',`password`='" + this.ippasswordfield.getText() + "' WHERE  id = '" + ipid + "'";
//                    stmt.execute(query);
//                    this.ipidfield.setText(null);
//                    this.ipnamefield.setText(null);
//                    this.iprolefield.setText(null);
//                    this.ipcontactfield.setText(null);
//                    this.ipaddressfield.setText(null);
//                    this.ipusernamefield.setText(null);
//                    this.ippasswordfield.setText(null);
//
//                    ResultSet datas = stmt1.executeQuery("SELECT * FROM `user_accounts`");
//                    while (datas.next()) {
//                        count = 0;
//                        manageiptbl.removeRow(count);
//                        manageiptbl.addRow(new Object[]{datas.getString("id"), datas.getString("role"), datas.getString("Name"), datas.getString("contact_number"), datas.getString("address"), datas.getString("username"), datas.getString("password")});
//                    }
//
//                    con.close();
//                    JOptionPane.showMessageDialog(null, "Successfully Updated.", "Alert", JOptionPane.INFORMATION_MESSAGE);
//                }
//            } catch (HeadlessException | ClassNotFoundException | SQLException e) {
//                System.out.println(e.getMessage());
//            }
//        }
    }//GEN-LAST:event_manageipupdatebtnMouseClicked

    private void manageipdeletebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageipdeletebtnMouseClicked
        DefaultTableModel userTableModel = (DefaultTableModel) manageinventorytable.getModel();
        if (manageinventorytable.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "Unsuccessful!", "Alert", JOptionPane.ERROR_MESSAGE);
        } else {

            String ipid = (String) userTableModel.getValueAt(manageinventorytable.getSelectedRow(), 0);
            try {
                Class.forName("com.mysql.jdbc.Driver");
                try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_management_system", "root", "")) {
                    Statement stmt = con.createStatement();
                    String query = "DELETE FROM user_accounts WHERE id= " + ipid + "";
                    stmt.execute(query);
                    con.close();
                    JOptionPane.showMessageDialog(null, "Successfully Deleted.", "Alert", JOptionPane.INFORMATION_MESSAGE);
                    userTableModel.removeRow(manageinventorytable.getSelectedRow());
                }
            } catch (HeadlessException | ClassNotFoundException | SQLException e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(null, "Unsuccessful!", "Alert", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_manageipdeletebtnMouseClicked

    private void manageipupdatebtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageipupdatebtn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_manageipupdatebtn1MouseClicked

    private void manageipdeletebtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageipdeletebtn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_manageipdeletebtn1MouseClicked

    private void updateadminaccbtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateadminaccbtn2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_updateadminaccbtn2MouseClicked

    private void deleteadminaccbtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteadminaccbtn2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteadminaccbtn2MouseClicked

    private void managecashiertableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managecashiertableMouseClicked
        DefaultTableModel managecashiertbl = (DefaultTableModel) managecashiertable.getModel();

        String cashierid = (String) managecashiertbl.getValueAt(managecashiertable.getSelectedRow(), 0);
        String cashierrole = (String) managecashiertbl.getValueAt(managecashiertable.getSelectedRow(), 1);
        String cashiername = (String) managecashiertbl.getValueAt(managecashiertable.getSelectedRow(), 2);
        String cashiercontact = (String) managecashiertbl.getValueAt(managecashiertable.getSelectedRow(), 3);
        String cashieraddress = (String) managecashiertbl.getValueAt(managecashiertable.getSelectedRow(), 4);
        String cashierusername = (String) managecashiertbl.getValueAt(managecashiertable.getSelectedRow(), 5);
        String cashierpass = (String) managecashiertbl.getValueAt(managecashiertable.getSelectedRow(), 6);

        this.cashieridfield.setText(cashierid);
        this.cashiernamefield1.setText(cashiername);
        this.cashierrolefield.setText(cashierrole);
        this.cashiercontactfield.setText(cashiercontact);
        this.cashieraddressfield.setText(cashieraddress);
        this.cashierusernamefield.setText(cashierusername);
        this.cashierpasswordfield.setText(cashierpass);
    }//GEN-LAST:event_managecashiertableMouseClicked

    private void cashierupdatebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cashierupdatebtnMouseClicked
        DefaultTableModel managecashiertbl = (DefaultTableModel) managecashiertable.getModel();

        if ("".equals(cashieridfield.getText()) && "".equals(cashierrolefield.getText())) {
            JOptionPane.showMessageDialog(null, "No Selected Product!", "Alert", JOptionPane.ERROR_MESSAGE);
        } else {
            String cashierid = (String) managecashiertbl.getValueAt(managecashiertable.getSelectedRow(), 0);

            int count;
            try {
                Class.forName("com.mysql.jdbc.Driver");
                try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_management_system", "root", "")) {
                    Statement stmt = con.createStatement();
                    Statement stmt1 = con.createStatement();
                    String query = "UPDATE `user_accounts` SET `role`='" + this.cashierrolefield.getText() + "',`Name`='" + this.cashiernamefield1.getText() + "',`contact_number`='" + this.cashiercontactfield.getText() + "',`address`='" + this.cashieraddressfield.getText() + "',`username`='" + this.cashierusernamefield.getText() + "',`password`='" + this.cashierpasswordfield.getText() + "' WHERE  id = '" + cashierid + "'";
                    stmt.execute(query);
                    this.cashieridfield.setText(null);
                    this.cashiernamefield1.setText(null);
                    this.cashierrolefield.setText(null);
                    this.cashiercontactfield.setText(null);
                    this.cashieraddressfield.setText(null);
                    this.cashierusernamefield.setText(null);
                    this.cashierpasswordfield.setText(null);

                    ResultSet datas = stmt1.executeQuery("SELECT * FROM `user_accounts`");
                    while (datas.next()) {
                        count = 0;
                        managecashiertbl.removeRow(count);
                        managecashiertbl.addRow(new Object[]{datas.getString("id"), datas.getString("role"), datas.getString("Name"), datas.getString("contact_number"), datas.getString("address"), datas.getString("username"), datas.getString("password")});
                    }

                    con.close();
                    JOptionPane.showMessageDialog(null, "Successfully Updated.", "Alert", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (HeadlessException | ClassNotFoundException | SQLException e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_cashierupdatebtnMouseClicked

    private void cashierdeletebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cashierdeletebtnMouseClicked
        DefaultTableModel userTableModel = (DefaultTableModel) managecashiertable.getModel();
        if (managecashiertable.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "Unsuccessful!", "Alert", JOptionPane.ERROR_MESSAGE);
        } else {

            String cashierid = (String) userTableModel.getValueAt(managecashiertable.getSelectedRow(), 0);
            try {
                Class.forName("com.mysql.jdbc.Driver");
                try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_management_system", "root", "")) {
                    Statement stmt = con.createStatement();
                    String query = "DELETE FROM user_accounts WHERE id= " + cashierid + "";
                    stmt.execute(query);
                    con.close();
                    JOptionPane.showMessageDialog(null, "Successfully Deleted.", "Alert", JOptionPane.INFORMATION_MESSAGE);
                    userTableModel.removeRow(managecashiertable.getSelectedRow());
                }
            } catch (HeadlessException | ClassNotFoundException | SQLException e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(null, "Unsuccessful!", "Alert", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_cashierdeletebtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressfield;
    private javax.swing.JTextField cashieraddressfield;
    private javax.swing.JTextField cashiercontactfield;
    private javax.swing.JButton cashierdeletebtn;
    private javax.swing.JTextField cashieridfield;
    private javax.swing.JTextField cashiernamefield1;
    private javax.swing.JTextField cashierpasswordfield;
    private javax.swing.JTextField cashierrolefield;
    private javax.swing.JButton cashierupdatebtn;
    private javax.swing.JTextField cashierusernamefield;
    private javax.swing.JTextField contactfield;
    private javax.swing.JButton deleteadminaccbtn;
    private javax.swing.JButton deleteadminaccbtn1;
    private javax.swing.JButton deleteadminaccbtn2;
    private javax.swing.JPanel dunnopanel;
    private javax.swing.JTextField idfield;
    private javax.swing.JTextField ipaddressfield;
    private javax.swing.JTextField ipcontactfield;
    private javax.swing.JTextField ipidfield;
    private javax.swing.JTextField ipnamefield;
    private javax.swing.JTextField ippasswordfield;
    private javax.swing.JTextField iprolefield;
    private javax.swing.JTextField ipusernamefield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel manageadminacc;
    private javax.swing.JButton manageadminbtn;
    private javax.swing.JTable manageadmintable;
    private javax.swing.JPanel managecashieracc;
    private javax.swing.JButton managecashierbtn;
    private javax.swing.JTable managecashiertable;
    private javax.swing.JButton manageexitbtn;
    private javax.swing.JPanel manageinventoryacc;
    private javax.swing.JButton manageinventorybtn;
    private javax.swing.JTable manageinventorytable;
    private javax.swing.JButton manageipdeletebtn;
    private javax.swing.JButton manageipdeletebtn1;
    private javax.swing.JButton manageipupdatebtn;
    private javax.swing.JButton manageipupdatebtn1;
    private javax.swing.JTextField namefield;
    private javax.swing.JTextField passwordfield;
    private javax.swing.JTextField rolefield;
    private javax.swing.JButton updateadminaccbtn;
    private javax.swing.JButton updateadminaccbtn1;
    private javax.swing.JButton updateadminaccbtn2;
    private javax.swing.JTextField usernamefield;
    // End of variables declaration//GEN-END:variables
}
