/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginregister;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ManageInventory extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form SystemProducts
     */
    public ManageInventory() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        inventorydisplaytransaction();
        manageInventory();
        displayproducts();
        datetransactiondisplay();
    }

    public void displayproducts() {
        DefaultTableModel producttable = (DefaultTableModel) tableproductdisplay.getModel();
        int count = 0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_management_system", "root", "")) {
                Statement stmt = con.createStatement();

                ResultSet datas = stmt.executeQuery("SELECT * FROM `products`");
                while (datas.next()) {
                    count = 1;
                    producttable.addRow(new Object[]{datas.getString("productID"), datas.getString("productName"), datas.getString("productPrice"), datas.getString("quantity"), datas.getString("description")});

                }
            }
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    public void manageInventory() {
        DefaultTableModel producttable = (DefaultTableModel) manageinventorytable.getModel();
        int count = 0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_management_system", "root", "")) {
                Statement stmt = con.createStatement();

                ResultSet datas = stmt.executeQuery("SELECT * FROM `products`");
                while (datas.next()) {
                    count = 1;
                    producttable.addRow(new Object[]{datas.getString("productID"), datas.getString("productName"), datas.getString("productPrice"), datas.getString("quantity"), datas.getString("description")});

                }
            }
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    public void inventorydisplaytransaction() {
        DefaultTableModel trasacttable = (DefaultTableModel) inventorytransactiotable.getModel();
        int count = 0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_management_system", "root", "")) {
                Statement stmt = con.createStatement();

                ResultSet datas = stmt.executeQuery("SELECT * FROM `product_sold`");
                while (datas.next()) {
                    count = 1;
                    trasacttable.addRow(new Object[]{datas.getString("date"), datas.getString("productName"), datas.getString("productQuantity"), datas.getString("totalPrice")});

                }
            }
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    public void datetransactiondisplay() {
        DefaultTableModel producttable = (DefaultTableModel) transactionDateTable.getModel();
        int count = 0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_management_system", "root", "")) {
                Statement stmt = con.createStatement();

                ResultSet datas = stmt.executeQuery("SELECT `date` FROM `product_sold`");
                while (datas.next()) {
                    count = 1;
                    producttable.addRow(new Object[]{datas.getString("date")});

                }
            }
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    
    
    
    

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        productsbtn = new javax.swing.JButton();
        manageinventorybtn = new javax.swing.JButton();
        adminlogoutbtn = new javax.swing.JButton();
        businesstransactionbtn = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        productDisplay = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableproductdisplay = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        manageinventory = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        manageinventorytable = new javax.swing.JTable();
        inventoryaddbtn = new javax.swing.JButton();
        inventorydeletebtn = new javax.swing.JButton();
        inventoryupdatebtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        productnamefield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        productidfield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        productquantityfield = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        productpricefield = new javax.swing.JTextField();
        productdescriptionfield = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        transactionDisplay = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inventorytransactiotable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        transactionDateTable = new javax.swing.JTable();
        deleteTransactionbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Courier New", 3, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inventory Management System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(213, 213, 213))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 80));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        productsbtn.setText("Our Products");
        productsbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productsbtnMouseClicked(evt);
            }
        });

        manageinventorybtn.setText("Manage Inventory");
        manageinventorybtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageinventorybtnMouseClicked(evt);
            }
        });

        adminlogoutbtn.setText("Logout");
        adminlogoutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminlogoutbtnMouseClicked(evt);
            }
        });

        businesstransactionbtn.setText("Business Transaction");
        businesstransactionbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                businesstransactionbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageinventorybtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productsbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adminlogoutbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(businesstransactionbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(productsbtn)
                .addGap(39, 39, 39)
                .addComponent(manageinventorybtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(businesstransactionbtn)
                .addGap(28, 28, 28)
                .addComponent(adminlogoutbtn)
                .addGap(45, 45, 45))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 280, 170, 290));

        tableproductdisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductID", "Product Name", "Product Price", "Available Quantity", "Description"
            }
        ));
        jScrollPane1.setViewportView(tableproductdisplay);

        jPanel7.setBackground(new java.awt.Color(0, 102, 51));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Our Agricultural Products");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(126, 126, 126))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 303, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout productDisplayLayout = new javax.swing.GroupLayout(productDisplay);
        productDisplay.setLayout(productDisplayLayout);
        productDisplayLayout.setHorizontalGroup(
            productDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        productDisplayLayout.setVerticalGroup(
            productDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("", productDisplay);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(0, 102, 0));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Courier New", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setText(" Manage Inventory");
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 380, 60));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 611, 58));

        manageinventorytable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductID", "Product Name", "Product Price", "Available Quantity", "Description"
            }
        ));
        manageinventorytable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageinventorytableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(manageinventorytable);

        jPanel8.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 65, 891, 221));

        inventoryaddbtn.setText("Add Stock");
        inventoryaddbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryaddbtnMouseClicked(evt);
            }
        });
        jPanel8.add(inventoryaddbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, -1, -1));

        inventorydeletebtn.setText("Delete");
        inventorydeletebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventorydeletebtnMouseClicked(evt);
            }
        });
        jPanel8.add(inventorydeletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, -1, -1));

        inventoryupdatebtn.setText("Update");
        inventoryupdatebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryupdatebtnMouseClicked(evt);
            }
        });
        inventoryupdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryupdatebtnActionPerformed(evt);
            }
        });
        jPanel8.add(inventoryupdatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, -1, -1));

        jLabel5.setText("ProductID: ");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 322, -1, -1));
        jPanel8.add(productnamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 183, -1));

        jLabel6.setText("Product Name:");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 354, -1, -1));
        jPanel8.add(productidfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 183, -1));

        jLabel7.setText("Product Price:");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));
        jPanel8.add(productquantityfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 183, -1));

        jLabel8.setText("Available Quantity:");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, -1, -1));
        jPanel8.add(productpricefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 183, -1));
        jPanel8.add(productdescriptionfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 450, -1));

        jLabel9.setText("Description:");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, -1));

        javax.swing.GroupLayout manageinventoryLayout = new javax.swing.GroupLayout(manageinventory);
        manageinventory.setLayout(manageinventoryLayout);
        manageinventoryLayout.setHorizontalGroup(
            manageinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageinventoryLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        manageinventoryLayout.setVerticalGroup(
            manageinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("", manageinventory);

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(0, 102, 0));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Courier New", 3, 35)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 255, 204));
        jLabel14.setText("Your Business Transaction");
        jPanel12.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 570, 60));

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 627, 60));

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inventorytransactiotable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Product Sold", "Quantity", "Total  "
            }
        ));
        jScrollPane2.setViewportView(inventorytransactiotable);

        jPanel13.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 230));

        transactionDateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date of Transaction"
            }
        ));
        jScrollPane4.setViewportView(transactionDateTable);

        jPanel13.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 310, 170));

        deleteTransactionbtn.setText("Delete Transaction");
        deleteTransactionbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteTransactionbtnMouseClicked(evt);
            }
        });
        jPanel13.add(deleteTransactionbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, -1, -1));

        jPanel11.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 910, 460));

        javax.swing.GroupLayout transactionDisplayLayout = new javax.swing.GroupLayout(transactionDisplay);
        transactionDisplay.setLayout(transactionDisplayLayout);
        transactionDisplayLayout.setHorizontalGroup(
            transactionDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
        );
        transactionDisplayLayout.setVerticalGroup(
            transactionDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("", transactionDisplay);

        jPanel3.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 920, 560));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1120, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productsbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsbtnMouseClicked
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_productsbtnMouseClicked

    private void manageinventorybtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageinventorybtnMouseClicked
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_manageinventorybtnMouseClicked

    private void adminlogoutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminlogoutbtnMouseClicked
        new LogInPageforUsers().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_adminlogoutbtnMouseClicked

    private void manageinventorytableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageinventorytableMouseClicked
        DefaultTableModel inventoryTableModel = (DefaultTableModel) manageinventorytable.getModel();

        String proid = (String) inventoryTableModel.getValueAt(manageinventorytable.getSelectedRow(), 0);
        String proname = (String) inventoryTableModel.getValueAt(manageinventorytable.getSelectedRow(), 1);
        String proprice = (String) inventoryTableModel.getValueAt(manageinventorytable.getSelectedRow(), 2);
        String proquantity = (String) inventoryTableModel.getValueAt(manageinventorytable.getSelectedRow(), 3);
        String prodescription = (String) inventoryTableModel.getValueAt(manageinventorytable.getSelectedRow(), 4);

        this.productidfield.setText(proid);
        this.productnamefield.setText(proname);
        this.productpricefield.setText(proprice);
        this.productquantityfield.setText(proquantity);
        this.productdescriptionfield.setText(prodescription);

    }//GEN-LAST:event_manageinventorytableMouseClicked

    private void inventoryaddbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryaddbtnMouseClicked

        DefaultTableModel manageinventorytablemodel = (DefaultTableModel) manageinventorytable.getModel();
        int count;
        try {
            String sql = "INSERT INTO `products`" + "(`productID`, `productName`, `productPrice`, `quantity`, `description`)" + " VALUES " + "(?, ?, ?, ?, ?)";

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_management_system", "root", "");
            pst = con.prepareStatement(sql);

            pst.setString(1, productidfield.getText());
            pst.setString(2, productnamefield.getText());
            pst.setString(3, productpricefield.getText());
            pst.setString(4, productquantityfield.getText());
            pst.setString(5, productdescriptionfield.getText());
            pst.executeUpdate();
           
            

            
            JOptionPane.showMessageDialog(null, "Successfully Added Data.", "Alert", JOptionPane.INFORMATION_MESSAGE);

            Statement stmt = con.createStatement();
            Statement stmt1 = con.createStatement();
            ResultSet datas = stmt1.executeQuery("SELECT * FROM `products`");
            while (datas.next()) {
                count = 0;
                manageinventorytablemodel.removeRow(count);
                manageinventorytablemodel.addRow(new Object[]{datas.getString("productID"), datas.getString("productName"), datas.getString("productPrice"), datas.getString("quantity"), datas.getString("description")});
            }

        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_inventoryaddbtnMouseClicked

    private void inventoryupdatebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryupdatebtnMouseClicked

        DefaultTableModel manageinventtablemodel = (DefaultTableModel) manageinventorytable.getModel();

        if ("".equals(productnamefield.getText()) && "".equals(productpricefield.getText())) {
            JOptionPane.showMessageDialog(null, "No Selected Product!", "Alert", JOptionPane.ERROR_MESSAGE);
        } else {
            String proid = (String) manageinventtablemodel.getValueAt(manageinventorytable.getSelectedRow(), 0);

            int count;
            try {
                Class.forName("com.mysql.jdbc.Driver");
                try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_management_system", "root", "")) {
                    Statement stmt = con.createStatement();
                    Statement stmt1 = con.createStatement();
                    String query = "UPDATE `products` SET `productName`='" + this.productnamefield.getText() + "',`productPrice`='" + this.productpricefield.getText() + "',`quantity`='" + this.productquantityfield.getText() + "',`description`='" + this.productdescriptionfield.getText() + "' WHERE  productID = '" + proid + "'";
                    stmt.execute(query);
                    this.productidfield.setText(null);
                    this.productnamefield.setText(null);
                    this.productpricefield.setText(null);
                    this.productquantityfield.setText(null);
                    this.productdescriptionfield.setText(null);

                    ResultSet datas = stmt1.executeQuery("SELECT * FROM `products`");
                    while (datas.next()) {
                        count = 0;
                        manageinventtablemodel.removeRow(count);
                        manageinventtablemodel.addRow(new Object[]{datas.getString("productID"), datas.getString("productName"), datas.getString("productPrice"), datas.getString("quantity"), datas.getString("description")});
                    }

                    con.close();
                    JOptionPane.showMessageDialog(null, "Successfully Updated.", "Alert", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (HeadlessException | ClassNotFoundException | SQLException e) {
                System.out.println(e.getMessage());
            }
        }


    }//GEN-LAST:event_inventoryupdatebtnMouseClicked

    private void inventorydeletebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventorydeletebtnMouseClicked
        DefaultTableModel inventoryTableModel = (DefaultTableModel) manageinventorytable.getModel();
        if (manageinventorytable.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "Unsuccessful!", "Alert", JOptionPane.ERROR_MESSAGE);
        } else {

            String inventoryproid = (String) inventoryTableModel.getValueAt(manageinventorytable.getSelectedRow(), 0);
            try {
                Class.forName("com.mysql.jdbc.Driver");
                try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_management_system", "root", "")) {
                    Statement stmt = con.createStatement();
                    String query = "DELETE FROM products WHERE productID= " + inventoryproid + "";
                    stmt.execute(query);
                    con.close();
                    JOptionPane.showMessageDialog(null, "Successfully Deleted.", "Alert", JOptionPane.INFORMATION_MESSAGE);
                    inventoryTableModel.removeRow(manageinventorytable.getSelectedRow());
                    
                    this.productidfield.setText(null);
                    this.productnamefield.setText(null);
                    this.productpricefield.setText(null);
                    this.productquantityfield.setText(null);
                    this.productdescriptionfield.setText(null);
                }
            } catch (HeadlessException | ClassNotFoundException | SQLException e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(null, "Unsuccessful!", "Alert", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_inventorydeletebtnMouseClicked

    private void businesstransactionbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_businesstransactionbtnMouseClicked
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_businesstransactionbtnMouseClicked

    private void deleteTransactionbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteTransactionbtnMouseClicked
        DefaultTableModel deletetransactTableModel = (DefaultTableModel) inventorytransactiotable.getModel();
        if (inventorytransactiotable.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "Unsuccessful!", "Alert", JOptionPane.ERROR_MESSAGE);
        } else {

            String deleteid = (String) deletetransactTableModel.getValueAt(manageinventorytable.getSelectedRow(), 0);
            try {
                Class.forName("com.mysql.jdbc.Driver");
                try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_management_system", "root", "")) {
                    Statement stmt = con.createStatement();
                    String query = "DELETE FROM product_sold WHERE id= " + deleteid + "";
                    stmt.execute(query);
                    con.close();
                    JOptionPane.showMessageDialog(null, "Successfully Deleted.", "Alert", JOptionPane.INFORMATION_MESSAGE);
                    deletetransactTableModel.removeRow(inventorytransactiotable.getSelectedRow());
                    
                }
            } catch (HeadlessException | ClassNotFoundException | SQLException e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(null, "Unsuccessful!", "Alert", JOptionPane.ERROR_MESSAGE);
            }
        }  
        
    }//GEN-LAST:event_deleteTransactionbtnMouseClicked

    private void inventoryupdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryupdatebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventoryupdatebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageInventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminlogoutbtn;
    private javax.swing.JButton businesstransactionbtn;
    private javax.swing.JButton deleteTransactionbtn;
    private javax.swing.JButton inventoryaddbtn;
    private javax.swing.JButton inventorydeletebtn;
    private javax.swing.JTable inventorytransactiotable;
    private javax.swing.JButton inventoryupdatebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel manageinventory;
    private javax.swing.JButton manageinventorybtn;
    private javax.swing.JTable manageinventorytable;
    private javax.swing.JPanel productDisplay;
    private javax.swing.JTextField productdescriptionfield;
    private javax.swing.JTextField productidfield;
    private javax.swing.JTextField productnamefield;
    private javax.swing.JTextField productpricefield;
    private javax.swing.JTextField productquantityfield;
    private javax.swing.JButton productsbtn;
    private javax.swing.JTable tableproductdisplay;
    private javax.swing.JTable transactionDateTable;
    private javax.swing.JPanel transactionDisplay;
    // End of variables declaration//GEN-END:variables
}
